/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-12 22:43:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.video;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class videoname_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1644705390126L));
    _jspx_dependants.put("jar:file:/E:/project/득근득근_JSP프로젝트/LastTeamProject3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Team3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1644705390131L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1644705390129L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644705389956L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>SHOP | 득근득근케어일기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.14.0/css/all.css\" integrity=\"sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc\" crossorigin=\"anonymous\">\r\n");
      out.write(" \r\n");
      out.write("<script src=\"/team3/asset/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/team3/asset/css/video.css/video.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("      #content {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 1900px;\r\n");
      out.write("      }\r\n");
      out.write("      #container {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>");
      out.write("\r\n");
      out.write("	   <!-- location -->\r\n");
      out.write("    <div id=\"inc-location\">\r\n");
      out.write("      <div>득근영상</div>\r\n");
      out.write("      <div>\r\n");
      out.write("        메인\r\n");
      out.write("        <i class=\"fas fa-angle-right\"></i>\r\n");
      out.write("        득근영상\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- content  -->\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("      <div id=\"container\">\r\n");
      out.write("        <!-- 영상 카테고리 : 영양학 -->\r\n");
      out.write("        <div id=\"content1\" class=\"all_content\">\r\n");
      out.write("          <div id=\"category1\" class=\"video_category\">\r\n");
      out.write("            득근득근과 함께하는 영양학\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 영양학 영상 갯수 & 정렬 -->\r\n");
      out.write("          <div id=\"info1\" class=\"video_info\">\r\n");
      out.write("            <b>5개</b>의 영상이 있습니다.\r\n");
      out.write("            <ui class=\"list\">\r\n");
      out.write("              <li class=\"order\">\r\n");
      out.write("                <a href='/team3/video/name.do' target=\"_self\">이름순</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href='/team3/video/reg.do' target=\"_self\">등록순</a></li>\r\n");
      out.write("            </ui>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 영양학 영상 & 유튭 링크  -->\r\n");
      out.write("          <div id=\"video1\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=yhfw8tIoZ4s&t=220s\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title1.webp\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video2\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=wOFtFfYBVSI\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title5.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video3\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=FZsbF9PpluM\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title3.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video4\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=9-9-cnqHG8Q\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title2.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 영양학 영상 제목 & 유튭 링크 -->\r\n");
      out.write("          <div id=\"title1\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=yhfw8tIoZ4s&t=220s\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle1\"\r\n");
      out.write("            >\r\n");
      out.write("              국내 최정상 스포츠영양사가 알려주는 \"탄수화물\"이란</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title2\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=wOFtFfYBVSI\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle2\"\r\n");
      out.write("            >\r\n");
      out.write("              기초부터 알아보는 우수한 영양상담 지방 ( feat.포화&불포화)</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title3\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=FZsbF9PpluM\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle3\"\r\n");
      out.write("            >\r\n");
      out.write("              운동 후 최적의 영양섭취 가이드(feat.기회의창)</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title4\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=9-9-cnqHG8Q\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle4\"\r\n");
      out.write("            >\r\n");
      out.write("              트레이너 출신 스포츠영양사가 알려주는 단백질 천하통일 총정리 1</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 영양학 두번째 줄 영상 & 제목 & 링크 -->\r\n");
      out.write("          <div id=\"video5\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=XQ5V1NEO-R0\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title4.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"clear: both\"></div>\r\n");
      out.write("          <div id=\"title5\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=XQ5V1NEO-R0\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle5\"\r\n");
      out.write("            >\r\n");
      out.write("              [우수한 영양상담] 나트륨</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 영상 카테고리 : 보충제 -->\r\n");
      out.write("        <div id=\"content2\" class=\"all_content\">\r\n");
      out.write("          <div id=\"category2\" class=\"video_category\">도움이 되는 보충제</div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 보충제 영상 갯수 & 정렬 -->\r\n");
      out.write("          <div id=\"info2\" class=\"video_info\">\r\n");
      out.write("            <b>5개</b>의 영상이 있습니다.\r\n");
      out.write("            <ui class=\"list\">\r\n");
      out.write("              <li class=\"order\">\r\n");
      out.write("                 <a href='/team3/video/name.do' target=\"_self\">이름순</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href='/team3/video/reg.do' target=\"_self\">등록순</a></li>\r\n");
      out.write("            </ui>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 보충제 영상 & 유튭 링크 -->\r\n");
      out.write("          <div id=\"video6\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=Dj3kYRr5zDo\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title10.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video7\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=-yLtnBU42Vw\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title6.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video8\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=VnsTna_ZGBI\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title9.jpg\" width=\"230\" height=\"129.38\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video9\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=TKwIH9IvM6c\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title7.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- 보충제 영상 제목 & 유튭 링크 -->\r\n");
      out.write("          <div id=\"title6\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=Dj3kYRr5zDo\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle6\"\r\n");
      out.write("            >\r\n");
      out.write("              김계란이 추천하는 운동 전,후 영양제</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title7\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=-yLtnBU42Vw\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle7\"\r\n");
      out.write("            >\r\n");
      out.write("              단백질 보충제 선택의 모든것!</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title8\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=VnsTna_ZGBI\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle8\"\r\n");
      out.write("            >\r\n");
      out.write("              보충제 시장 1등급 고인물 스포츠영양사의 국산vs외국 단백질 보충제\r\n");
      out.write("              전격비교</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title9\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=TKwIH9IvM6c\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle9\"\r\n");
      out.write("            >\r\n");
      out.write("              약사가 선택한 단백질보충제, 동물성이냐 식물성이냐 그것이\r\n");
      out.write("              알고싶다!</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 보충제 두번째 줄 영상 & 제목 & 링크 -->\r\n");
      out.write("          <div id=\"video10\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=8j58DptAB3w\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title8.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"clear: both\"></div>\r\n");
      out.write("          <div id=\"title11\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=8j58DptAB3w\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle10\"\r\n");
      out.write("            >\r\n");
      out.write("              종결) 영양제, 보조제는 딱 이것들만 드세요 !!!!!</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 영상 카테고리 : 식단관리 -->\r\n");
      out.write("        <div id=\"content3\" class=\"all_content\">\r\n");
      out.write("          <div id=\"category3\" class=\"video_category\">효과적인 식단 관리</div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 식단관리 영상 갯수 & 정렬 -->\r\n");
      out.write("          <div id=\"info3\" class=\"video_info\">\r\n");
      out.write("            <b>5개</b>의 영상이 있습니다.\r\n");
      out.write("            <ui class=\"list\">\r\n");
      out.write("              <li class=\"order\">\r\n");
      out.write("               <a href='/team3/video/name.do' target=\"_self\">이름순</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href='/team3/video/reg.do' target=\"_self\">등록순</a></li>\r\n");
      out.write("            </ui>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 식단관리 영상 & 유튭 링크 -->\r\n");
      out.write("          <div id=\"video11\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=Mt8ll1FACAA\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title13.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video12\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=AgX7yqQcb_k\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title15.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video13\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=lTBPAjs2BtA\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title11.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"video14\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=nuEvLCD5j6c\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title14.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 식단관리 영상 제목 & 유튭 링크 -->\r\n");
      out.write("          <div id=\"title11\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=Mt8ll1FACAA\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle11\"\r\n");
      out.write("            >\r\n");
      out.write("              무조건 감량 가능한 참가자들의 다이어트 식단공개</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title12\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=AgX7yqQcb_k\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle12\"\r\n");
      out.write("            >\r\n");
      out.write("              살 빼기 힘든 식단 vs 효과적인 다이어트식단 🔥63kg에서 44kg! 식단\r\n");
      out.write("              공개</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title13\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=lTBPAjs2BtA\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle13\"\r\n");
      out.write("            >\r\n");
      out.write("              식단 이대로 해보세요. 식단 짜는 방법 !</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"title14\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=nuEvLCD5j6c\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle14\"\r\n");
      out.write("            >\r\n");
      out.write("              체지방 3% 만드는 대회식단 완벽 대 공개!</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 식단관리 두번째 줄 영상 & 제목 & 링크 -->\r\n");
      out.write("          <div id=\"video15\" class=\"video_content\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=y4vZ44rGxUw\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle15\"\r\n");
      out.write("            >\r\n");
      out.write("              <img src=\"/team3/asset/images/title12.jpg\" width=\"230\"\r\n");
      out.write("            /></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"clear: both\"></div>\r\n");
      out.write("          <div id=\"title16\" class=\"video_title\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"https://www.youtube.com/watch?v=y4vZ44rGxUw\"\r\n");
      out.write("              target=\"_blank\"\r\n");
      out.write("              id=\"atitle16\"\r\n");
      out.write("            >\r\n");
      out.write("              최초 식단 공개! 다이어트 30년 노하우 공개! l 최고의 다이어트\r\n");
      out.write("              Ep.1</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    <div id=\"inc-footer\">\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div id=\"footer-top\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#!\">고객센터</a></li>\r\n");
      out.write("                    <li><a href=\"#!\">이용약관</a></li>\r\n");
      out.write("                    <li><a href=\"#!\">개인정보처리방침</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"line_ccc\"></div>\r\n");
      out.write("            <div id=\"footer-bottom\">\r\n");
      out.write("                <div>고객센터 070-9999-8888</div>\r\n");
      out.write("                <div>득근득근케어일기 | (주)득근득근 | 대표: 김득근 | 개인정보보호책임자: 왕근육 | E-mail: admin@deukgeun.com</div>\r\n");
      out.write("                <div>서울특별시 강남구 근육로 3대 500, (득근빌딩)</div>\r\n");
      out.write("                <div>사업자등록번호:100-01-11111 사업자정보 확인 > 통신판매업신고 </div>\r\n");
      out.write("                <div>&copy; Deukgeun, Inc.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("   	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(6,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${grade eq '관리자'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 관리자헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                    	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 득근! |\r\n");
          out.write("                        <a href=\"/team3/admin/membermanagement/membermanagement.do\">&nbsp;관리메뉴</a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/member/logout.do\">로그아웃</a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/mypage/myordersearch.do\">주문내역</a>&nbsp;|&nbsp;\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(63,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                    	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 득근! |\r\n");
          out.write("                        <a href=\"/team3/member/logout.do\">&nbsp;로그아웃 </a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/mypage/myordersearch.do\">주문조회 </a>&nbsp;|&nbsp; \r\n");
          out.write("                        <a href=\"/team3/cscenter/frequentqa.do\">고객센터</a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(120,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 비회원헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                        <a href=\"/team3/member/login.do\">로그인 </a>&nbsp;|&nbsp; \r\n");
          out.write("                         <a href=\"/team3/member/signup.do\">회원가입 </a>&nbsp;|&nbsp; \r\n");
          out.write("                        <a href=\"/team3/cscenter/frequentqa.do\">고객센터</a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
