/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-12 22:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1644705390126L));
    _jspx_dependants.put("jar:file:/E:/project/득근득근_JSP프로젝트/LastTeamProject3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Team3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644705389956L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>SHOP | 득근득근케어일기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.14.0/css/all.css\" integrity=\"sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc\" crossorigin=\"anonymous\">\r\n");
      out.write(" \r\n");
      out.write("<script src=\"/team3/asset/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("	    #content{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            /* box-sizing: border-box; */\r\n");
      out.write("        }\r\n");
      out.write("        #container{\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            margin-bottom: 200px;\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            /* box-sizing: border-box; */\r\n");
      out.write("        }\r\n");
      out.write("		 #inc-header > .header > header > #logo{\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("        }\r\n");
      out.write("        .line {\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("            border-bottom: 1px solid #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        #next {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("        }\r\n");
      out.write("        #loginid, #loginpw {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 15px auto;\r\n");
      out.write("        }\r\n");
      out.write("        #loginid > div:nth-child(1), #loginpw > div:nth-child(1) {\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            width: 15%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("            background-color: rgb(233, 233, 233);\r\n");
      out.write("        }\r\n");
      out.write("        #loginid > input[type=text], #loginpw > input[type=password] {\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            width: 85%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #fail {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: tomato;\r\n");
      out.write("        }\r\n");
      out.write("        #mbsearch {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 15px auto;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("        #mbsearch > a {\r\n");
      out.write("            color: cornflowerblue;\r\n");
      out.write("        }\r\n");
      out.write("        #next > input[type=submit] {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            background-color: cornflowerblue;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 10px 0px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        #next > input[type=button] {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: cornflowerblue;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 10px 0px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        #next > div:nth-child(4) {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: rgb(121, 121, 121);\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("    <div id=\"inc-header\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
      out.write("            </header>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>  \r\n");
      out.write("    <!-- content  -->\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("        	<form method=\"POST\" action=\"/team3/member/loginok.do\">\r\n");
      out.write("                <div id=\"loginid\">\r\n");
      out.write("                    <div><i class=\"far fa-keyboard\"></i></div>\r\n");
      out.write("                    <input type=\"text\" name=\"id\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"loginpw\">\r\n");
      out.write("                    <div><i class=\"fas fa-key\"></i></div>\r\n");
      out.write("                    <input type=\"password\" name=\"pw\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div id=\"fail\">아이디 또는 비밀번호를 다시 확인하세요.<br>등록되지 않은 아이디이거나, 아이디 또는 비밀번호를 잘못 입력하셨습니다.</div> -->\r\n");
      out.write("                <div id=\"mbsearch\"><a href=\"/team3/member/findid.do\">아이디/비밀번호 찾기 ></a></div>\r\n");
      out.write("                <div id=\"next\">\r\n");
      out.write("                    <input type=\"submit\" value=\"로그인\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <input type=\"button\" value=\"회원가입\" onclick=\"location.href='/team3/member/signup.do';\">\r\n");
      out.write("                    <div>&copy; Deukgeun, Inc.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
