/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-12 22:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1644705390126L));
    _jspx_dependants.put("jar:file:/E:/project/득근득근_JSP프로젝트/LastTeamProject3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Team3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1644705390131L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1644705390129L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644705389956L));
    _jspx_dependants.put("jar:file:/E:/project/득근득근_JSP프로젝트/LastTeamProject3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Team3/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>SHOP | 득근득근케어일기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/team3/asset/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.14.0/css/all.css\" integrity=\"sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc\" crossorigin=\"anonymous\">\r\n");
      out.write(" \r\n");
      out.write("<script src=\"/team3/asset/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        #content{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            /* box-sizing: border-box; */\r\n");
      out.write("        }\r\n");
      out.write("        #container{\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            /* box-sizing: border-box; */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabBox {\r\n");
      out.write("         width: 1000px;\r\n");
      out.write("         margin: 0 auto;\r\n");
      out.write("         font-size: 22px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .reviewCount,\r\n");
      out.write("      .productQACount {\r\n");
      out.write("         color: red;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area {\r\n");
      out.write("         width: 1000px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area h2 {\r\n");
      out.write("         font-size: 20px;\r\n");
      out.write("         padding: 10px 5px;\r\n");
      out.write("         border-bottom: 1px solid #000;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area table th,\r\n");
      out.write("      #order_delivery_area table td {\r\n");
      out.write("         font-size: 14px;\r\n");
      out.write("         font-weight: normal;\r\n");
      out.write("         border-bottom: 1px solid #e6e6e6;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area table th {\r\n");
      out.write("         width: 160px;\r\n");
      out.write("         background: #f8f8f8;\r\n");
      out.write("         padding: 24px;\r\n");
      out.write("         vertical-align: top;\r\n");
      out.write("         word-break: keep-all;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area table td {\r\n");
      out.write("         padding: 20px 24px 20px 40px;\r\n");
      out.write("         line-height: 24px;\r\n");
      out.write("         word-break: keep-all;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area h2.bottom_t {\r\n");
      out.write("         padding-top: 54px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #order_delivery_area table.bottom td {\r\n");
      out.write("         font-size: 13px;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/team3/asset/css/productList/productDetail.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>");
      out.write("\r\n");
      out.write("    	   	\r\n");
      out.write("    <!-- content -->\r\n");
      out.write("                    <!-- 상품이미지 & 리뷰 -->\r\n");
      out.write("                       <div class=\"itemContentBox\">\r\n");
      out.write("                            <div class=\"itemContentImage\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.producturl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\r\n");
      out.write("                            \r\n");
      out.write("                                <div class=\"reviewContent\">\r\n");
      out.write("                                    <span class=\"reviewStar\">\r\n");
      out.write("                                            <img src=\"/team3/asset/images/star.png\" alt=\"별점\">\r\n");
      out.write("                                            <img src=\"/team3/asset/images/star.png\" alt=\"별점\">\r\n");
      out.write("                                            <img src=\"/team3/asset/images/star.png\" alt=\"별점\">\r\n");
      out.write("                                            <img src=\"/team3/asset/images/star.png\" alt=\"별점\">\r\n");
      out.write("                                            <img src=\"/team3/asset/images/star_off.png\" alt=\"별점\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    <span class=\"reviewScore\">4.5</span>\r\n");
      out.write("                                    <span class=\"reviews\"> 리뷰수 </span>\r\n");
      out.write("                                    <span class=\"reviewsCount\">1</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    <!-- 상품주문 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"itemOrderContentBox\">\r\n");
      out.write("                                <div class=\"orderItemTitle\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"orderItem\">\r\n");
      out.write("                                <span class=\"orderItemPrice\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write(" </span>\r\n");
      out.write("                                    <span class=\"orderItemPriceUnit\">원</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              \r\n");
      out.write("                                <div class=\"delivery\">\r\n");
      out.write("                                    <span class=\"deliveryTitle\">배송방법</span>\r\n");
      out.write("                                    <span class=\"deliveryCityPrice\">3,000원 (20,000원이상 무료배송)\r\n");
      out.write("                                    <span class=\"deliveryCountryPrice\">/ 도서산간지역4,000원</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                  \r\n");
      out.write("\r\n");
      out.write("                            <div class=\"itemOptionChoose\">\r\n");
      out.write("                                        \r\n");
      out.write("							<form method=\"GET\" action=\"/team3/basket/add.do\" id=\"get\">\r\n");
      out.write("							\r\n");
      out.write("                                            <select id=\"OptionMenuList\" name=\"select\">\r\n");
      out.write("	                                            <option value=\"none\" selected hidden>상품옵션선택</option>\r\n");
      out.write("	                                            <option value=\"10\">10팩(+0원)</option>\r\n");
      out.write("	                                            <option value=\"30\">30팩 (+");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("원)</option>\r\n");
      out.write("	                                            <option value=\"50\">50팩 (+");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("원)</option>\r\n");
      out.write("	                                            <option value=\"100\">100팩 (+");
      if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_page_context))
        return;
      out.write("원)</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                             \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"itemPriceTotal\">\r\n");
      out.write("                                    <span class=\"itemPriceTotalText\">총 상품금액 </span>\r\n");
      out.write("                                    <span class=\"itemPriceTotalNum\">0</span>\r\n");
      out.write("                                    <span class=\"itemPriceTotalUnit\">원</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("                            <div class=\"itemOptionBtn\">\r\n");
      out.write("                                <span class=\"itemOptionCartBtnArea\">\r\n");
      out.write("                                <input type=\"submit\" value=\"장바구니\" class=\"itemOptionCartBtn\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <input type=\"hidden\" name=\"productseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"productseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                            </form>\r\n");
      out.write("								\r\n");
      out.write("                                <span class=\"itemOptionOrderBtnArea\">\r\n");
      out.write("                                <input type=\"submit\" value=\"바로구매\" class=\"itemOptionOrderBtn\" onclick=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>      \r\n");
      out.write("                        </div>\r\n");
      out.write("                  \r\n");
      out.write("           \r\n");
      out.write("                    <!-- 메뉴 탭 -->\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"itemMenuTab\">\r\n");
      out.write("                        <nav>\r\n");
      out.write("                            <li id=\"itemInfo\">상품정보</li>\r\n");
      out.write("                            <li id=\"orderReview\">구매후기<span class=\"reviewCount\">(1)</span></li>\r\n");
      out.write("                            <li id=\"productQA\">상품문의<span class=\"productQACount\">(1)</span></li>\r\n");
      out.write("                            <li id=\"deliveryCS\">배송안내</li>\r\n");
      out.write("                         </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                   <!-- 메뉴 탭 상세내용 -->\r\n");
      out.write("   <div class=\"itemDetail\">\r\n");
      out.write("    <img src=\"/team3/asset/images/itemDetail(1).jpg\" alt=\"\">\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" <!-- 구매 후기 -->\r\n");
      out.write(" <div id=\"order_reviews_area\" class=\"tabBox\" style=\"flex-direction: column;\">\r\n");
      out.write("    <div class=\"tabBox\"\r\n");
      out.write("       style=\"display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid black; padding-bottom: 5px;\">\r\n");
      out.write("       <div>구매후기<span style=\"color: red;\">(1)</span>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div><input type=\"button\" value=\"후기작성\"\r\n");
      out.write("             style=\"background-color: #3A4C67; color: white; width: 100px; height: 40px; cursor: pointer;\">\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"tabBox\" style=\"margin-top: 30px; padding-bottom: 5px; border-bottom: 1px solid #DDDDDD;\">\r\n");
      out.write("          <ul style=\"list-style: disc; padding: 0;\">\r\n");
      out.write("             <li style=\"margin-left: 20px; font-size: 14px;\">득근득근 케어 다이어리는 믿을 수 있는 후기관리를 위해 회원으로 가입되신 실제 구매자만 후기를 작성하실\r\n");
      out.write("                수\r\n");
      out.write("                있습니다.</li>\r\n");
      out.write("             <li style=\"margin-left: 20px; font-size: 14px;\">구매하신 상품을 받으신 후, 후기를 남겨주시면 상품의 엄정함에 도움이 됩니다.</li>\r\n");
      out.write("             <li style=\"margin-left: 20px; font-size: 14px;\">상품과 관련 없는 후기 혹은 욕설, 비방, 부적절한 단어, 문의글, 양도글, 광고성, 도배, 환불처리된\r\n");
      out.write("                주문,\r\n");
      out.write("                개인정보가 포함된 후기는 예고없이 블라인드 처리 될 수 있습니다.</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("       <div style=\"margin-top: 10px; padding-bottom: 5px; border-bottom: 1px solid #DDDDDD;\">\r\n");
      out.write("          <div style=\"font-size: 12px; color: #666;\">(5점) pop** 2022.01.25</div>\r\n");
      out.write("          <div style=\"font-size: 12px; color: #666;\">단백질 섭취를 위해서 구매한건데 맛도 좋고 가격도 저렴한 것 같아요!</div>\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- 상품 문의 -->\r\n");
      out.write(" \r\n");
      out.write(" <div id=\"order_inquiry_area\" class=\"tabBox\" style=\"flex-direction: column;\">\r\n");
      out.write("    <div class=\"tabBox\"\r\n");
      out.write("       style=\"display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid black; padding-bottom: 5px;\">\r\n");
      out.write("       <div>상품문의<span style=\"color: red;\">(1)</span>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div><input type=\"button\" value=\"문의작성\"\r\n");
      out.write("             style=\"background-color: #3A4C67; color: white; width: 100px; height: 40px; cursor: pointer;\">\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tabBox\" style=\"margin-top: 30px; padding-bottom: 5px; border-bottom: 1px solid #DDDDDD;\">\r\n");
      out.write("       <ul style=\"list-style: disc; padding: 0;\">\r\n");
      out.write("          <li style=\"margin-left: 20px; font-size: 14px;\">상품문의에서는 상품과 무관한 요청은 처리되지 않습니다.</li>\r\n");
      out.write("          <li style=\"margin-left: 20px; font-size: 14px;\">배송문의·취소·환불 등은 1:1상담게시판을 통해 문의남겨주시기 바랍니다.</li>\r\n");
      out.write("          <li style=\"margin-left: 20px; font-size: 14px;\">미구매,비방이나 양도 광고성, 욕설, 도배글, 개인정보가 포함된 글은 예고없이 삭제되거나 노출이 제한될 수 있습니다.</li>\r\n");
      out.write("       </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"qaForm\">\r\n");
      out.write("       <form action=\"\">\r\n");
      out.write("          <p>득근득근에 문의하기</p>\r\n");
      out.write("          <div>\r\n");
      out.write("             <textarea></textarea>\r\n");
      out.write("             <input type=\"submit\">\r\n");
      out.write("          </div>\r\n");
      out.write("       </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"qa\">\r\n");
      out.write("       <div id=\"userId\">'asdf1234'님 문의</div>\r\n");
      out.write("       <div class=\"question\">\r\n");
      out.write("          <div><i class=\"fab fa-quora\"></i></div>\r\n");
      out.write("          <div>\r\n");
      out.write("             안녕하세요 스테이크 제품에 합성보존료가 들어갔는지 궁금하고 복합조미식품1,2,3이라고 나오던데 이것들이 정확하게 어떤 성분인지 자료와 함께 알 수 있을까요?\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("             2021.10.14           \r\n");
      out.write("          </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"answer\">\r\n");
      out.write("          <div>\r\n");
      out.write("             <i class=\"fas fa-angle-double-right\"></i>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("             문의주신 맛있닭 닭가슴살 스테이크에는 합성보존제는 함유되지않습니다.<br>\r\n");
      out.write("             복합조미식품으로 원재료함량에 표기된 부분에 대해서는 아쉽게도 상세 제조정보를 드리기는 어렵습니다.<br>\r\n");
      out.write("             가공제품의 원재료 함량 표기 시, 제조사에서 투입되는 모든 원료가 기재됩니다.\r\n");
      out.write("          </div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- // 상품 문의 -->\r\n");
      out.write("\r\n");
      out.write(" <!-- 배송안내 -->\r\n");
      out.write(" <div id=\"order_delivery_area\" class=\"tabBox\">\r\n");
      out.write("    <table style=\"width: 45%;\">\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"width: 20%; vertical-align: middle\">배송 방법</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">CJ대한통운(1588-1255), 롯데택배(1588-2121), 로젠택배(1588-9988) </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"vertical-align: middle;\">배송 지역</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">전국</td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"vertical-align: middle;\">배송 비용</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">3,000원 (20,000원이상 무료배송)<br>\r\n");
      out.write("             제주도 및 도서산간 지역 추가 운임 : 4,000원</td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"vertical-align: middle;\">배송 기간</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">결제(입금)일로부터 1~2일 후 (주말/공휴일 제외)</td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"vertical-align: middle;\">배송 마감</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">오후 5시 (월~금요일 / 제주, 도서산간 : 목요일)<br>\r\n");
      out.write("             마감시간 이전 주문·결제 시 당일 발송<br>\r\n");
      out.write("             마감시간 이후 주문·결제 시 다음날 발송<br>\r\n");
      out.write("             (주말·공휴일 결제 시 다음 영업일에 발송)<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"vertical-align: middle;\">주말 출고</th>\r\n");
      out.write("          <td style=\"vertical-align: middle;\">- 목요일 배송 마감 시간 이후 주문은 금요일 출고되어 토요일에 배송됩니다.<br>\r\n");
      out.write("             - 토요일 수령이 어려우신 고객님께서는 배송 메시지에 “월요일출고” 라고 적어주시면 월요일에 출고되어 화요일에 받아보실 수 있습니다. (공휴일인 경우 다음 영업일 출고)<br>\r\n");
      out.write("             ※ 야채 및 개별 출고일정을 따르는 제품은 제외<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <table class=\"bottom\" style=\"width: 55%;\">\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\"width: 20%; vertical-align: middle\">주의사항</th>\r\n");
      out.write("          <td style=\" vertical-align: middle\">- 본 상품은 제품 특성상 단순 변심에 의한 교환 · 반품은 불가합니다.<br>\r\n");
      out.write("             - 군부대, 사서함 주소의 경우 배송이 안될 수 있으니 고객센터 확인 후 주문 바랍니다.<br>\r\n");
      out.write("             (구매 전 제품 상세 및 배송 · 반품에 대한 내용을 확인해 주세요.)<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\" vertical-align: middle\">교환/반품 신청</th>\r\n");
      out.write("          <td style=\" vertical-align: middle\">제품의 교환 및 반품 시 고객센터 담당자에게 교환 또는 반품 신청을 해주시기 바랍니다.<br>\r\n");
      out.write("             (전화 : 070-8984-5771 / 홈페이지 고객센터)<br>\r\n");
      out.write("             <br>\r\n");
      out.write("             - 교환 및 반품은 고객센터 담당자와 협의를 통해 이루어지며, 임의로 수취거부 및 반송하는 경우 반품 처리되지 않습니다.<br>\r\n");
      out.write("             - 냉동/냉장 식품의 경우 제품의 특성상 ‘단순변심’에 의한 반품 및 환불은 불가합니다.<br>\r\n");
      out.write("             주문전 충분히 제품 상세페이지 및 제품 설명을 참고하시고 주문바랍니다. <br>\r\n");
      out.write("             - N페이 결제건은 출고/반품 주소지가 상품별로 상이하여, 자동 수거 지시 기능이 불가합니다.\r\n");
      out.write("          </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\" vertical-align: middle\">교환/반품이 가능한 경우</th>\r\n");
      out.write("          <td style=\" vertical-align: middle\">- 주문한 제품과 다르거나 판매자의 제공정보와 상이한 경우<br>\r\n");
      out.write("             - 제품이 불량이거나 손상된 경우<br>\r\n");
      out.write("             - 배송사의 귀책 사유에 따른 배송 지연 발생 및 제품이 변질 된 경우<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\" vertical-align: middle\">교환/반품이 불가능한 경우</th>\r\n");
      out.write("          <td style=\" vertical-align: middle\">- 판매자와 교환/반품에 대한 협의 없이 임의로 폐기 처분 또는 반품/배송한 경우<br>\r\n");
      out.write("             - 냉동·냉장 보관 식품 및 채소, 유통기한이 2개월 미만인 상품에 대한 단순 변심의 경우<br>\r\n");
      out.write("             - 잘못된 주소나 연락처 기재로 인한 반송 또는 고객의 부재로 인해 배송이 지연되어 제품이 변질된 경우<br>\r\n");
      out.write("             - 수령 후, 보관/취급 부주의로 인해 제품이 변질 또는 손상된 경우<br>\r\n");
      out.write("             - PC 및 휴대폰의 화면과 실제 상품의 색상이나 이미지 차이 또는 개인적 취향이나 기호에 따른 교환/반품<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("          <th style=\" vertical-align: middle\">교환/반품 절차</th>\r\n");
      out.write("          <td style=\" vertical-align: middle\">- 전화 및 이메일을 통해 반송처 및 교환/반품 방법을 안내해드립니다.<br>\r\n");
      out.write("             - 반품시 결제방식에 따라 카드 승인취소 또는 계좌입금 처리를 해드립니다.<br></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("    </table>\r\n");
      out.write(" </div>                                                                                              \r\n");
      out.write("\r\n");
      out.write("   <!-- footer -->\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    <div id=\"inc-footer\">\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div id=\"footer-top\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#!\">고객센터</a></li>\r\n");
      out.write("                    <li><a href=\"#!\">이용약관</a></li>\r\n");
      out.write("                    <li><a href=\"#!\">개인정보처리방침</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"line_ccc\"></div>\r\n");
      out.write("            <div id=\"footer-bottom\">\r\n");
      out.write("                <div>고객센터 070-9999-8888</div>\r\n");
      out.write("                <div>득근득근케어일기 | (주)득근득근 | 대표: 김득근 | 개인정보보호책임자: 왕근육 | E-mail: admin@deukgeun.com</div>\r\n");
      out.write("                <div>서울특별시 강남구 근육로 3대 500, (득근빌딩)</div>\r\n");
      out.write("                <div>사업자등록번호:100-01-11111 사업자정보 확인 > 통신판매업신고 </div>\r\n");
      out.write("                <div>&copy; Deukgeun, Inc.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write(" //탭1 상품정보 클릭\r\n");
      out.write(" $('#itemInfo').click(function () {\r\n");
      out.write("         //보여야 할 것\r\n");
      out.write("         $('.itemDetail').css('display', 'block');\r\n");
      out.write("         //닫아야 할 것\r\n");
      out.write("         $('#order_reviews_area').css('display', 'none');\r\n");
      out.write("         $('#order_inquiry_area').css('display', 'none');\r\n");
      out.write("         $('#order_delivery_area').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("         //선택탭 색 조정\r\n");
      out.write("         $('#itemInfo').css('background-color', 'RGB(85,85,85)');\r\n");
      out.write("\r\n");
      out.write("         //비 선택 > 기존 색\r\n");
      out.write("         $('#orderReview').css('background-color', 'white');\r\n");
      out.write("         $('#productQA').css('background-color', 'white');\r\n");
      out.write("         $('#deliveryCS').css('background-color', 'white');\r\n");
      out.write("\r\n");
      out.write("         //선택 색깔\r\n");
      out.write("         $('#itemInfo').css('color', 'white');\r\n");
      out.write("\r\n");
      out.write("         //비선택 색깔\r\n");
      out.write("         $('#orderReview').css('color', 'black');\r\n");
      out.write("         $('#productQA').css('color', 'black');\r\n");
      out.write("         $('#deliveryCS').css('color', 'black');\r\n");
      out.write("\r\n");
      out.write("         $('.reviewCount').css('color', 'red');\r\n");
      out.write("         $('.productQACount').css('color', 'red');\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //-----------------탭2 상품후기  클릭\r\n");
      out.write("      $('#orderReview').click(function () {\r\n");
      out.write("         //보여야 할 것\r\n");
      out.write("         $('#order_reviews_area').css('display', 'flex');\r\n");
      out.write("         //닫아야 할 것\r\n");
      out.write("         $('.itemDetail').css('display', 'none');\r\n");
      out.write("         $('#order_inquiry_area').css('display', 'none');\r\n");
      out.write("         $('#order_delivery_area').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("         //선택탭 배경색 조정\r\n");
      out.write("         $('#orderReview').css('background-color', 'RGB(85,85,85)');\r\n");
      out.write("         //비 선택 > 배경기존 색\r\n");
      out.write("\r\n");
      out.write("         $('#itemInfo').css('background-color', 'white');\r\n");
      out.write("         $('#productQA').css('background-color', 'white');\r\n");
      out.write("         $('#deliveryCS').css('background-color', 'white');\r\n");
      out.write("\r\n");
      out.write("         //선택 색깔\r\n");
      out.write("         $('#orderReview').css('color', 'white');\r\n");
      out.write("         $('.reviewCount').css('color', 'yellow');\r\n");
      out.write("         //비선택 색깔\r\n");
      out.write("         $('#itemInfo').css('color', 'black');\r\n");
      out.write("         $('#productQA').css('color', 'black');\r\n");
      out.write("         $('#deliveryCS').css('color', 'black');\r\n");
      out.write("         $('.productQACount').css('color', 'red');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("      //탭3 상품문의  클릭\r\n");
      out.write("      $('#productQA').click(function () {\r\n");
      out.write("         //보여야 할 것\r\n");
      out.write("         $('#order_inquiry_area').css('display', 'flex');\r\n");
      out.write("         //닫아야 할 것\r\n");
      out.write("         $('.itemDetail').css('display', 'none');\r\n");
      out.write("         $('#order_reviews_area').css('display', 'none');\r\n");
      out.write("         $('#order_delivery_area').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("         //선택탭 색 조정\r\n");
      out.write("         $('#productQA').css('background-color', 'RGB(85,85,85)');\r\n");
      out.write("         //비 선택 > 기존 색\r\n");
      out.write("         $('.itemDetail').css('background-color', 'white');\r\n");
      out.write("         $('#orderReview').css('background-color', 'white');\r\n");
      out.write("         $('#deliveryCS').css('background-color', 'white');\r\n");
      out.write("\r\n");
      out.write("         //선택 색깔\r\n");
      out.write("         $('#productQA').css('color', 'white');\r\n");
      out.write("         $('.productQACount').css('color', 'yellow');\r\n");
      out.write("\r\n");
      out.write("         //비선택 색깔\r\n");
      out.write("         $('#itemInfo').css('color', 'black');\r\n");
      out.write("         $('#orderReview').css('color', 'black');\r\n");
      out.write("         $('#deliveryCS').css('color', 'black');\r\n");
      out.write("         $('.reviewCount').css('color', 'red');\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("      //탭4 배송안내  클릭\r\n");
      out.write("      $('#deliveryCS').click(function () {\r\n");
      out.write("         //보여야 할 것\r\n");
      out.write("         $('#order_delivery_area').css('display', 'flex');\r\n");
      out.write("         //닫아야 할 것\r\n");
      out.write("         $('#order_reviews_area').css('display', 'none');\r\n");
      out.write("         $('#order_inquiry_area').css('display', 'none');\r\n");
      out.write("         $('#order_productInfo_area').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("         //선택탭 색 조정\r\n");
      out.write("         $('#deliveryCS').css('background-color', 'RGB(85,85,85)');\r\n");
      out.write("         //비 선택 > 기존 색\r\n");
      out.write("         $('#itemInfo').css('background-color', 'white');\r\n");
      out.write("         $('#orderReview').css('background-color', 'white');\r\n");
      out.write("         $('#productQA').css('background-color', 'white');\r\n");
      out.write("\r\n");
      out.write("         //선택 색깔\r\n");
      out.write("         $('#deliveryCS').css('color', 'white');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         //비선택 색깔\r\n");
      out.write("         $('#itemInfo').css('color', 'black');\r\n");
      out.write("         $('#orderReview').css('color', 'black');\r\n");
      out.write("         $('#productQA').css('color', 'black');\r\n");
      out.write("         $('.reviewCount').css('color', 'red');\r\n");
      out.write("         $('.productQACount').css('color', 'red');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //가격처리\r\n");
      out.write("\r\n");
      out.write("      var price = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      $('#OptionMenuList').change(function(){\r\n");
      out.write("         var selnum = $('#OptionMenuList Option:selected').val();\r\n");
      out.write("\r\n");
      out.write("         var result;\r\n");
      out.write("         \r\n");
      out.write("         if (selnum == 10) {\r\n");
      out.write("            result = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("         } else if(selnum == 30) {\r\n");
      out.write("            result = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price30}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("         } else if(selnum == 50) {\r\n");
      out.write("            result = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price50}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("         } else if(selnum == 100)   { \r\n");
      out.write("            result = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("         } else {\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("    \r\n");
      out.write("         $('.itemPriceTotalNum').html(result.toLocaleString());\r\n");
      out.write("         $('.orderItemPrice').html(result.toLocaleString());\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("      //탭\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("   	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(6,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${grade eq '관리자'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 관리자헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                    	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 득근! |\r\n");
          out.write("                        <a href=\"/team3/admin/membermanagement/membermanagement.do\">&nbsp;관리메뉴</a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/member/logout.do\">로그아웃</a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/mypage/myordersearch.do\">주문내역</a>&nbsp;|&nbsp;\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(63,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                    	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 득근! |\r\n");
          out.write("                        <a href=\"/team3/member/logout.do\">&nbsp;로그아웃 </a>&nbsp;|&nbsp;\r\n");
          out.write("                        <a href=\"/team3/mypage/myordersearch.do\">주문조회 </a>&nbsp;|&nbsp; \r\n");
          out.write("                        <a href=\"/team3/cscenter/frequentqa.do\">고객센터</a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/inc/header.jsp(120,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 비회원헤더 -->\r\n");
          out.write("    \r\n");
          out.write("    <div id=\"inc-header\">\r\n");
          out.write("        \r\n");
          out.write("        <div class=\"header\">\r\n");
          out.write("        \r\n");
          out.write("        \r\n");
          out.write("            <form action=\"productlist.do\" method=\"get\">\r\n");
          out.write("          \r\n");
          out.write("                <header>\r\n");
          out.write("              \r\n");
          out.write("                    <div id=\"logo\"><a href=\"/team3/main.do\"><img src=\"/team3/asset/images/logo1.png\" alt=\"로고\"><span id=\"first\">득근득근</span><br>케어일기</a></div>\r\n");
          out.write("                   \r\n");
          out.write("                    \r\n");
          out.write("                \r\n");
          out.write("                    <div id=\"search\"><input value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchkeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" input type=\"text\" name=\"searchkeyword\" placeholder=\"검색하기\"><a href=\"\"><i class=\"fas fa-search\" style=\"font-size:1.5rem; margin-left: 2.3rem;\"></i></a></div>\r\n");
          out.write("                 \r\n");
          out.write("          \r\n");
          out.write("                    <div id=\"menu\">\r\n");
          out.write("                        <a href=\"/team3/member/login.do\">로그인 </a>&nbsp;|&nbsp; \r\n");
          out.write("                         <a href=\"/team3/member/signup.do\">회원가입 </a>&nbsp;|&nbsp; \r\n");
          out.write("                        <a href=\"/team3/cscenter/frequentqa.do\">고객센터</a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </header>\r\n");
          out.write("            </form>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_ccc\"></div>\r\n");
          out.write("        <div class=\"nav\">\r\n");
          out.write("            <nav>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <a href=\"#!\"><i class=\"fas fa-bars\" style=\"margin-right: 1rem;\"></i>전체 카테고리</a>\r\n");
          out.write("                    <ul id=\"drop-category\">\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=닭가슴살';\">닭가슴살</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=도시락';\">도시락</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=야채류';\">야채류</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=단백질보충제';\">단백질보충제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=기타영양제';\">기타영양제</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=영양별';\">영양별 상품조회</li>\r\n");
          out.write("                        <li onclick=\"location.href='product/productlist.do?category=개인별';\">개인별 상품조회</li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">베스트</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"#!\">신상품</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/healthcare/healthcaremain.do\">헬스케어</a></div>\r\n");
          out.write("                <div class=\"main-nav\"><a href=\"/team3/video/name.do\">득근영상</a></div>\r\n");
          out.write("                <div class=\"side\">\r\n");
          out.write("                    <div><a href=\"/team3/mypage/myordersearch.do\"><i class=\"fas fa-user-circle\"></i></a></div>\r\n");
          out.write("                    <div><a href=\"/team3/basket/list.do\"><i class=\"fas fa-shopping-cart\"></i></a></div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </nav>\r\n");
          out.write("        </div>\r\n");
          out.write("        <div class=\"line_black\"></div>\r\n");
          out.write("    </div>\r\n");
          out.write("    <!-- 회원헤더 -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/product/productdetail.jsp(112,61) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price10}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/product/productdetail.jsp(112,61) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/product/productdetail.jsp(131,70) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${diffrentPrice30}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/product/productdetail.jsp(131,70) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /WEB-INF/views/product/productdetail.jsp(132,70) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${diffrentPrice50}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/product/productdetail.jsp(132,70) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
      // /WEB-INF/views/product/productdetail.jsp(133,72) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${diffrentPrice100}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/product/productdetail.jsp(133,72) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
      _jspx_th_fmt_005fformatNumber_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
    }
    return false;
  }
}
